import { Metadata } from 'next';
import MapSection from '../../common/layout/Map/MapSection';
import Navbar from '../../common/layout/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  return (
    <main className="flex items-stretch min-h-screen">
      <Navbar />
      <MapSection />
      {auth && auth}
    </main>
  );
}
