import { poppins } from '@/fonts/Poppins';
import classNames from 'classnames';
import { Metadata } from 'next';
import '../common/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(poppins.className)}>
        <main>{children}</main>
      </body>
    </html>
  );
}
